### ISSUE TITLE
Add option to get Base64 decoded resources

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/geostore#140]
Resources can hold base64-encoded images.
Having an option to retrieve the resource already decoded will enable the images to be directly linked in browsers. (adding a request parameter, e.g. /resources/resource/5/data?toBinary=true).

A better solution should be to make GeoStore to save data as blob (maybe supporting multipart upload) to store/retrieve directly binary files, but it shoud require more work

**Comment by etj** [comment]
Data are retrieved using the /data/ context.
Added a method mapped onto  ``/data/{ID}/raw``, accepting a query param ``decode``, which at the moment only accepts ``base64`` as value.

**Comment by etj** [comment]
It would probably be useful to add a ``DATA_URI`` value for ``decode``, which tries and parses the blob as a [data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) (``data:[<media type>][;base64],<data>``), automatically decoding the data and setting a ``Content-type``  header as the one contained in the data URI.

**Comment by etj** [comment]
As reported in the [REST API wiki page](https://github.com/geosolutions-it/geostore/wiki/REST-API#data)

- /data/{id}/raw GET
   - param decode: (optional) decodes the raw content before returning it. Available values:
      - base64: decode the whole blob as a base64 encoded string an return binary data
      - datauri: check the format of the data URI, decodes it an returns the decoded data with the proper 
        Content-type header.
