### ISSUE TITLE
Pagination in search do not work properly

### ISSUE THREAD

**Issue by offtherailz** [geosolutions-it/geostore#141]
example: 
```
http://mapstore2.geo-solutions.it/mapstore/rest/geostore/extjs/search/category/MAP/***/?start=0&limit=10
```
returns `"totalCount": 25` but only 7 results

```
http://mapstore2.geo-solutions.it/mapstore/rest/geostore/extjs/search/category/MAP/***/?start=0&limit=20

```
 only 15 results and not in the same order.

**Comment by etj** [comment]
The ``page`` and ``limit`` are used in the DB query, **then** the result list is checked for authorization, so you may get less records than counted.

We should fix:
- retrieval and authorization
- count functions
