### ISSUE TITLE
Slow responses to extjs search queries

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/geostore#161]
The response time of the request
/extjs/search/category/MAP/***/thumbnail?start=0&limit=12
grows with the number of maps with a thumbnail

A setup with 16 maps, 5 with thumbnails has a response time of ~450 ms
with 10 thumbnails, the response time is ~ 700ms

A setup with 43 maps (29 with thumbnails) is experiencing 6 seconds of response time.

**Comment by offtherailz** [comment]
Thumbnail in that search is only an attribute. 
Maybe saving the thumbnails in GeoStore resources slows down in general the db or the search functionality?
Another possibility is that the search ReST searches also on the thumbnail attribute, but as I said it is only an attribute, so it shouldn't take that long.

**Comment by Gnafu** [comment]
GeoStore is making a huge number of queries to the database to check the resource's permission.

**Comment by etj** [comment]
Biggest problem is in user/usergroups eager fetching, which shows the "N+1 selects" problem.

**Comment by Gnafu** [comment]
Preliminary tests confirm the improvement.
Was there a possible issue with the groups? What was it?
Can we catch it with a test?

**Comment by Gnafu** [comment]
To test:
- [x] Create Group
- [x] Delete Group
- [x] Add user to group
- [x] Remove user from group
- [ ] Delete user linked to a group
- [ ] Delete a group linked to an user

**Comment by etj** [comment]
Useful links for adding tests against the n+1 select issue:
- https://vladmihalcea.com/2014/02/01/how-to-detect-the-n-plus-one-query-problem-during-testing/
