### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jordanfoy227** [geosolutions-it/geostore#224]
Hey, trying to follow along with the Build instructions from the wiki (https://github.com/geosolutions-it/geostore/wiki/Building-instructions#building-geostore-with-postgres-support), and I just have a couple questions (I don't know if I have problems yet) 

Is it necessary to do a full clean install of GeoStore (under the Quick GeoStore build and run with H2 in-memory DB# section)? 
I guess I am confused about what GeoStore actually does.

**Comment by offtherailz** [comment]
Hi @jordanfoy227 , Please write to the [MapStore mailing list](https://groups.google.com/g/mapstore-developers) for questions. 
Here we track only work on bugs and new features. Thank you for the patience.
