### ISSUE TITLE
Loading around 5k LDAP users at startup generates memory issues

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/geostore#290]
When MS is connected to LDAP with an high number of user/orgs (eg. 5k) there is memory overload at application startup.

At startup the GeoStoreInit class does a count on the number of users inside the repository to understand if eventually is needed to fill the repository with some default user https://github.com/geosolutions-it/geostore/blob/7973e7da7bbcc33f6ad2fface70304ef15475257/src/web/app/src/main/java/it/geosolutions/geostore/init/GeoStoreInit.java#L111

For the LDAP UserDAOImpl the count cause the loading of all the users in a list and then the size() method is called so that the Users are loaded in memory https://github.com/geosolutions-it/geostore/blob/110018b03f8f7f7ab8f2be0a3c59b1cedadd9b50/src/core/persistence/src/main/java/it/geosolutions/geostore/core/dao/ldap/impl/UserDAOImpl.java#L309

As we saw the UserGroupDAOImpl is assigning User to UserGroup everitime the UserGroups are retrieve while the UserDAOImpl is loading for each User its UserGroup using the UserGroupDAOImpl.
At startup for the count then we are going to have loaded in memory the whole list of users where each users has a List of UserGroups and each Group has in turn the list of Users to which is assigned causing the issue the client found

**Comment by taba90** [comment]
Will use a ISearch Wrapper to pass down to the DAO the context of the service requiring the UserGroups.
When the context is the UserService.class, the Users beloging to each UserGroup will not be added. When the context is UserGroupService the users will be instead added.
Estimate is **4** hours.

**Comment by taba90** [comment]
opened pr on main

**Comment by taba90** [comment]
@tdipisa pr merged on master.
I guess we need to backport to 1.8.x and do another geostore release could you confirm it?

**Comment by taba90** [comment]
backported to 1.8.x as well
